abstract: Vanilla Perl for win32
author: David A Golden <dagolden@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Perl-Dist-Vanilla
no_index: 
  directory: 
    - extra
    - bin
    - inc
    - t
requires: 
  Perl::Dist::Builder: 0.000003
version: 7
